### ISSUE TITLE
Compilation failure on recent nightly

### ISSUE THREAD

**Issue by michael-p** [rustsim/ncollide#266]
Trying to compile a project that indirectly depends on ncollide 0.17.3 (through kiss3d) yields the following compilation failure on rustc 1.34.0-nightly (f66e4697a 2019-02-20) on macOS:
```
error[E0034]: multiple applicable items in scope
   --> /Users/michaelp/.cargo/registry/src/github.com-1ecc6299db9ec823/ncollide3d-0.17.3/src/shape/shape.rs:103:14
    |
103 |         self.type_id() == TypeId::of::<T>()
    |              ^^^^^^^ multiple `type_id` found
    |
note: candidate #1 is defined in the trait `shape::shape::GetTypeId`
   --> /Users/michaelp/.cargo/registry/src/github.com-1ecc6299db9ec823/ncollide3d-0.17.3/src/shape/shape.rs:158:5
    |
158 |     fn type_id(&self) -> TypeId;
    |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    = help: to disambiguate the method call, write `shape::shape::GetTypeId::type_id(&self)` instead
note: candidate #2 is defined in the trait `std::any::Any`
    = help: to disambiguate the method call, write `std::any::Any::type_id(&self)` instead

error: aborting due to previous error
```

**Comment by sebcrozet** [comment]
Hi!

This issue is known to happen only on nightly. It has been fixed in ncollide 0.18 because a breaking change was necessary.

You should either switch to stable, or upgrade kiss3d (and thus ncollide indirectly) to its latest version.

Please reopen if the problem persists with the latest versions.

**Comment by michael-p** [comment]
Upgrading did indeed fix everything, thank you very much for your fast reply! (and also for all your other amazing work!)

**Comment by martinellison** [comment]
I'm still getting the error in stable. I have updated using cargo update. Have kiss3d and nalgebra been updated to pick up the new version in stable?

**Comment by sebcrozet** [comment]
@martinellison What version do you have written in your `Cargo.toml` for ncollide/kiss3d/nalgebra? My guess is that your `Cargo.toml` depends on an older version of kiss3d (perhaps v0.18) so a `cargo update` won't automatically update to the version 0.19 or 0.20.

**Comment by martinellison** [comment]
This builds now thanks.

**Comment by martinellison** [comment]
> kiss3d = "0.18.0"
> nalgebra = "0.17.2"
> spade = "1.7.0"
I'm not explicitly using ncollide. ncollide3d 0.18.4 is a dependency of kiss3d 0.18.0.

**Comment by proehlen** [comment]
Just a heads up that this is exact error is happening when using `ncollide2d = 0.17.0" [per the getting started page](https://ncollide.org/getting_started/).  I only found there was a later version by looking through the commits on the repo (I'm also a rust newbie).
