### ISSUE TITLE
Minimum size of a cuboid

### ISSUE THREAD

**Issue by pkrum** [rustsim/ncollide#275]
Hey guys, i'm using NCollide via Amethyst/NPhysics. First, thanks a lot for your awesome work!

I noticed following:
The documentation says, that each half-extent of a `Cuboid` must be greater than `0.04` but it is asserted to be just non-negative:

https://github.com/rustsim/ncollide/blob/d6fd1030c4a70cb2d2c369fea3e7cc30a8cea20b/src/shape/cuboid.rs#L23-L36

Is that limitation (half_extent > 0.04) necessary at all?
If yes, then this should be asserted, too.

**Comment by sebcrozet** [comment]
Hi! Looks like the doc is wrong. The half-extents only need to be positive.
