### ISSUE TITLE
Provide bounding volume methods without an isometry parameter

### ISSUE THREAD

**Issue by aleksijuvani** [rustsim/ncollide#283]
As discussed in #282. When doing AABB computations for triangles, passing in `Isometry::identity()` as the transform to the `aabb` method is expensive in the cases where we don't need to transform the shape. Therefore, we should provide a version of this method that doesn't take an isometry parameter.

**Comment by sebcrozet** [comment]
Thank you for opening this issue!

If think your suggestion was a good one: modify the `HasBoundingVolume` trait to add a method as follows: `fn local_bounding_volume(&self) -> BV;` that does not include the transform. This method won't make the type parameter `N` intervene, but don't think that will be an issue.

We could do something similar for other traits, like for example by adding a `local_support_point` to the [SupportMap](https://www.ncollide.org/rustdoc/ncollide3d/shape/trait.SupportMap.html) trait to avoid the transform. But that's out of the scope of this issue of course.


A long time ago, the `HasBoundingVolume` trait had an additional type parameter `M` (as shown is that [old version of bounding_volume.rs](https://github.com/rustsim/ncollide/blob/99ee70e31e1f45b874511d7301e47ad5c78f4986/ncollide_geometry/bounding_volume/bounding_volume.rs#L2)) for the transform type. This allowed the transform to be set as [Id](https://www.nalgebra.org/rustdoc/nalgebra/struct.Id.html) which represents the identity transformations with all its methods set to no-ops. This allowed to avoid the cost of the transformation when the transform is known at compile-time to be the identity. This capability disappeared when most type parameters except the numeric type `N` were removed from ncollide to make the API simpler. I don't want to re-add this type parameter, so the new `local_bounding_volume` method seems like the best approach.

**Comment by aleksijuvani** [comment]
After I had finished typing that, I was looking at the types that actually implement `HasBoundingVolume` and it occurred to me that it is only ever implemented for `AABB` and `BoundingSphere`. For bounding spheres the rotation component of the transform will do nothing, so this made me think that the performance impact of the transform can be negligible for bounding spheres. This made me second guess my suggestion, but maybe it still is a good one.

> A long time ago, the `HasBoundingVolume` trait had an additional type parameter `M` (as shown is that [old version of bounding_volume.rs](https://github.com/rustsim/ncollide/blob/99ee70e31e1f45b874511d7301e47ad5c78f4986/ncollide_geometry/bounding_volume/bounding_volume.rs#L2)) for the transform type. This allowed the transform to be set as [Id](https://www.nalgebra.org/rustdoc/nalgebra/struct.Id.html) which represents the identity transformations with all its methods set to no-ops. This allowed to avoid the cost of the transformation when the transform is known at compile-time to be the identity. This capability disappeared when most type parameters except the numeric type `N` were removed from ncollide to make the API simpler. I don't want to re-add this type parameter, so the new `local_bounding_volume` method seems like the best approach.

Interesting! While looking into this I did briefly wonder if nalgebra had some sort of compile-time optimization for identity elements.

**Comment by sebcrozet** [comment]
> For bounding spheres the rotation component of the transform will do nothing, so this made me think that the performance impact of the transform can be negligible for bounding spheres. This made me second guess my suggestion, but maybe it still is a good one.

I think your suggestion is still good because bounding spheres are a very special case. In the future we will have more bounding volume types (k-DOP, OBB, etc.) and most of thew will be rotation-dependent.
