### ISSUE TITLE
`Ball::project_point` is incorrect

### ISSUE THREAD

**Issue by whatisaphone** [rustsim/ncollide#314]
It looks like `Ball::project_point` is mishandling the radius.

```rust
let ball = Ball::new(5.0);
let point = Point3::new(50.0, 0.0, 0.0);
let projection = ball.project_point(&Isometry::identity(), &point, false);
panic!("{:?}", projection);
```

With a sphere of radius 5.0, I would expect a result of `[5, 0, 0]`, but instead I'm seeing `[1, 0, 0]`. That point is not on the surface of the sphere.

**Comment by sebcrozet** [comment]
Hi! I've seen this bug too while working on my `salva` branch. It will be fixed in the next version of ncollide which will be released this week.
